export const INDIAN_STATES_AND_UTS = [
  // States (28)
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories (8)
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const;

export const POPULAR_INDIAN_LOCATIONS = [
  { label: 'T Nagar, Chennai, TN', address: 'T Nagar, Chennai, Tamil Nadu', lat: 13.0418, lng: 80.2341 },
  { label: 'Anna Nagar, Chennai, TN', address: 'Anna Nagar, Chennai, Tamil Nadu', lat: 13.0850, lng: 80.2101 },
  { label: 'Velachery, Chennai, TN', address: 'Velachery, Chennai, Tamil Nadu', lat: 12.9757, lng: 80.2207 },
  { label: 'Indiranagar, Bengaluru, KA', address: 'Indiranagar, Bengaluru, Karnataka', lat: 12.9784, lng: 77.6408 },
  { label: 'Banjara Hills, Hyderabad, TS', address: 'Banjara Hills, Hyderabad, Telangana', lat: 17.4156, lng: 78.4411 },
  { label: 'Bandra, Mumbai, MH', address: 'Bandra West, Mumbai, Maharashtra', lat: 19.0596, lng: 72.8295 },
];
